name: Deploy
on:
  push:
    branches:
      - main
env:
  PROJECT_NAME: "portfolio"
  CARGO_TERM_COLOR: always
jobs:
  DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Setup Rust
        run: |
          rustup target add wasm32-unknown-unknown
          cargo clippy
          cargo fmt --check

      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.18.2/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

      - name: Build
        run: ./trunk build --release

      - name: Install Vercel CLI
        run: npm i -g vercel@latest 

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages publish dist/ --project-name "${{ env.PROJECT_NAME }}"
